name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy repo Fix (chỉ để lưu workflow, không dùng code trong đây)
      - name: Checkout this repo
        uses: actions/checkout@v4

      # Clone project gốc + submodule SDL, SDL_image, cpu_features, ...
      - name: Clone upstream CasioEmuMsvc
        run: |
          git clone --recursive https://github.com/telecomadm1145/CasioEmuMsvc.git srcdir
          cd srcdir
          git submodule update --init --recursive

          echo "== Patch scale UI =="
          # 1) Đổi defaultscale Android từ 3.0f thành 1.0f
          sed -i 's/constexpr float defaultscale = 3.0f;/constexpr float defaultscale = 1.0f;/g' CasioEmuMsvc/Gui/Gui.h

          # 2) Comment dòng style.ScaleAllSizes(3.0f);
          sed -i 's/style.ScaleAllSizes(3.0f);/\/\/ style.ScaleAllSizes(3.0f);/g' CasioEmuMsvc/Gui/Gui.h

      # JDK 21 vì trong build.gradle dùng JavaVersion.VERSION_21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        run: |
          cd srcdir
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: srcdir/app/build/outputs/apk/release/*.apk
